apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: acitojod
  name: acitojod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acitojod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acitojod
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
status: {}
