apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: afefaven
  name: afefaven
spec:
  replicas: 1
  selector:
    matchLabels:
      app: afefaven
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: afefaven
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
status: {}
