apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: anuwural
  name: anuwural
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anuwural
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: anuwural
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
status: {}
