apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: avebecam
  name: avebecam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avebecam
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: avebecam
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
status: {}
