apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: elucirid
  name: elucirid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elucirid
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: elucirid
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
status: {}
