apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: etimesub
  name: etimesub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etimesub
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: etimesub
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
status: {}
