apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: icehomoq
  name: icehomoq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icehomoq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: icehomoq
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
status: {}
