apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ijisonav
  name: ijisonav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ijisonav
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ijisonav
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
status: {}
