apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ipefojib
  name: ipefojib
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipefojib
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ipefojib
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
status: {}
