apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: iyarinuh
  name: iyarinuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iyarinuh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: iyarinuh
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
status: {}
