apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: obulusoc
  name: obulusoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obulusoc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: obulusoc
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
status: {}
