apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ofoyurow
  name: ofoyurow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ofoyurow
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ofoyurow
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
status: {}
