apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ofujalul
  name: ofujalul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ofujalul
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ofujalul
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
status: {}
