apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ohorunuy
  name: ohorunuy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ohorunuy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ohorunuy
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
status: {}
