apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ubehefar
  name: ubehefar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubehefar
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ubehefar
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
status: {}
