apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ukucokip
  name: ukucokip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ukucokip
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ukucokip
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
status: {}
