apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: uqakujov
  name: uqakujov
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uqakujov
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: uqakujov
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
status: {}
