apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: uxaqotaf
  name: uxaqotaf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uxaqotaf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: uxaqotaf
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
status: {}
